name: Build and Test Microservices

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: todoapp
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Eureka Server
        working-directory: eureka-server
        run: mvn clean install

      - name: Build API Gateway
        working-directory: api-gateway
        run: mvn clean install

      - name: Build Todo Service
        working-directory: todo-service
        run: mvn clean install

      - name: Build Notification Service
        working-directory: notification-service
        run: mvn clean install


      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


      - name: Build and Push Eureka Server Image
        run: |
          docker build -t sinjinxjohn/eureka-server:latest ./eureka-server
          docker push sinjinxjohn/eureka-server:latest

      - name: Build and Push API Gateway Image
        run: |
          docker build -t sinjinxjohn/api-gateway:latest ./api-gateway
          docker push sinjinxjohn/api-gateway:latest

      - name: Build and Push Todo Service Image
        run: |
          docker build -t sinjinxjohn/todo-service:latest ./todo-service
          docker push sinjinxjohn/todo-service:latest

      - name: Build and Push Notification Service Image
        run: |
          docker build -t sinjinxjohn/notification-service:latest ./notification-service
          docker push sinjinxjohn/notification-service:latest
      - name: Deploy to Docker
        run: |
          docker pull sinjinxjohn/eureka-server:latest
          docker pull sinjinxjohn/api-gateway:latest
          docker pull sinjinxjohn/todo-service:latest
          docker pull sinjinxjohn/notification-service:latest

          docker-compose -f docker-compose.yml up -d

